/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

public static String Restaurant (String() str) {
    Restaurant openNewRestaurant = new Restaurant();
        }
